#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'nginx'
# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

cookbook 'postgresql'
cookbook 'mongodb'
cookbook 'nodejs',
   git: 'https://github.com/redguide/nodejs'
cookbook 'rvm',
   git: 'https://github.com/fnichol/chef-rvm'
